// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PokeGame_MVC.Database.PokeGame;

public partial class Equipos
{
    public int Id { get; set; }

    public int UsuarioId { get; set; }

    public int PokedexId { get; set; }

    public string State { get; set; }

    public virtual Pokedex Pokedex { get; set; }

    public virtual Usuario Usuario { get; set; }
}