// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PokeGame_MVC.Database.PokeGame;

public partial class Mensajes
{
    public int Id { get; set; }

    public int RemitenteId { get; set; }

    public int DestinatarioId { get; set; }

    public string Contenido { get; set; }

    public DateTime FechaEnvio { get; set; }

    public virtual Usuario Destinatario { get; set; }

    public virtual Usuario Remitente { get; set; }
}