// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PokeGame_MVC.Database.PokeGame;

public partial class Pokemon
{
    public int Id { get; set; }

    public int IdUsuario { get; set; }

    public virtual ICollection<PokemonUsuario> PokemonUsuario { get; set; } = new List<PokemonUsuario>();
}