// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PokeGame_MVC.Database.PokeGame;

public partial class Pokedex
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Debilidad { get; set; }

    public string Tipo { get; set; }

    public string Evoluciones { get; set; }

    public string Peso { get; set; }

    public string Numero { get; set; }
}