// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PokeGame_MVC.Database.PokeGame;

public partial class Retos
{
    public int RetoId { get; set; }

    public int RetadorId { get; set; }

    public int RetadoId { get; set; }

    public string Estado { get; set; }

    public DateTime FechaEnvio { get; set; }

    public DateTime? FechaRespuesta { get; set; }

    public int? RetadorPokemonId { get; set; }

    public int? RetadoPokemonId { get; set; }

    public virtual Usuario Retado { get; set; }

    public virtual Pokedex RetadoPokemon { get; set; }

    public virtual Usuario Retador { get; set; }

    public virtual Pokedex RetadorPokemon { get; set; }
}