// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PokeGame_MVC.Database.PokeGame;

public partial class RolPermiso
{
    public int Id { get; set; }

    public int IdRol { get; set; }

    public int IdPermiso { get; set; }

    public virtual Permisos IdPermisoNavigation { get; set; }

    public virtual Rol IdRolNavigation { get; set; }
}