// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PokeGame_MVC.Database.PokeGame;

public partial class Usuario
{
    public int Id { get; set; }

    public int RolId { get; set; }

    public string Nombre { get; set; }

    public string PasswordHash { get; set; }

    public string Username { get; set; }

    public string FotoPerfil { get; set; }

    public DateTime FechaCreacion { get; set; }

    public string Email { get; set; }

    public virtual ICollection<PokemonUsuario> PokemonUsuario { get; set; } = new List<PokemonUsuario>();

    public virtual Rol Rol { get; set; }
}