// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PokeGame_MVC.Database.PokeGame;

public partial class Usuario
{
    public int Id { get; set; }

    public int RolId { get; set; }

    public string Nombre { get; set; }

    public string PasswordHash { get; set; }

    public string Username { get; set; }

    public string FotoPerfil { get; set; }

    public DateTime FechaCreacion { get; set; }

    public string Email { get; set; }

    public virtual ICollection<Enfermeria> EnfermeriaUsuarioAtiende { get; set; } = new List<Enfermeria>();

    public virtual ICollection<Enfermeria> EnfermeriaUsuarioSolicita { get; set; } = new List<Enfermeria>();

    public virtual ICollection<Equipos> Equipos { get; set; } = new List<Equipos>();

    public virtual ICollection<Mensajes> MensajesDestinatario { get; set; } = new List<Mensajes>();

    public virtual ICollection<Mensajes> MensajesRemitente { get; set; } = new List<Mensajes>();

    public virtual ICollection<Retos> RetosRetado { get; set; } = new List<Retos>();

    public virtual ICollection<Retos> RetosRetador { get; set; } = new List<Retos>();

    public virtual Rol Rol { get; set; }
}